################################################################################
# run_config.yml:
#   Contains config options for the Application Run:
#     corresponding default values to be updated
#
#   Loaded in:  ./initializers/zt_load_config.rb
#
#   11.10.2016  ZT
#   30.08.2017  'access_restricted' key is added
################################################################################
mail:
  bcc:  evgt@mail.ru

debug:
  status:  false

multilingual:
  status:  true

access_restricted:  false